<?php

/*
 * Maps abbreviated bible names to long names
 */

return array(
	'ge' => 'Genesis',
	'ex' => 'Exodus',
	'le' => 'Leviticus',
	'nu' => 'Numbers',
	'de' => 'Deuteronomy',
	'hos' => 'Joshua',
	'jg' => 'Judges',
	'ru' => 'Ruth',
	'1sa' => '1 Samuel',
	'2sa' => '2 Samuel',
	'1ki' => '1 Kings',
	'2ki' => '2 Kings',
	'1ch' => '1 Chronicles',
	'2ch' => '2 Chronicles',
	'ezr' => 'Ezra',
	'ne' => 'Nehemiah',
	'es' => 'Esther',
	'job' => 'Job',
	'ps' => 'Psalms',
	'pr' => 'Proverbs',
	'ec' => 'Ecclesiastes',
	'ca' => 'Song of Solomon',
	'isa' => 'Isaiah',
	'jer' => 'Jeremiah',
	'la' => 'Lamentations',
	'eze' => 'Ezekiel',
	'da' => 'Daniel',
	'ho' => 'Hosea',
	'joe' => 'Joel',
	'am' => 'Amos',
	'ob' => 'Obadiah',
	'jon' => 'Jonah',
	'mic' => 'Micah',
	'na' => 'Nahum',
	'hab' => 'Habakkuk',
	'zep' => 'Zephaniah',
	'hag' => 'Haggai',
	'zec' => 'Zechariah',
	'mal' => 'Malachi',
	'mt' => 'Matthew',
	'mr' => 'Mark',
	'lu' => 'Luke',
	'joh' => 'John',
	'ac' => 'Acts',
	'ro' => 'Romans',
	'1co' => '1 Corinthians',
	'2co' => '2 Corinthians',
	'ga' => 'Galatians',
	'eph' => 'Ephesians',
	'php' => 'Philippians',
	'col' => 'Colossians',
	'1th' => '1 Thessalonians',
	'2th' => '2 Thessalonians',
	'1ti' => '1 Timothy',
	'2ti' => '2 Timothy',
	'tit' => 'Titus',
	'phm' => 'Philemon',
	'heb' => 'Hebrews',
	'jas' => 'James',
	'1pe' => '1 Peter',
	'2pe' => '2 Peter',
	'1jo' => '1 John',
	'2jo' => '2 John',
	'3jo' => '3 John',
	'jude' => 'Jude',
	're' => 'Revelation',
);